import type {
  NavigationItem,
  QuickStartItem,
  ResearchPost,
  TrendingResearchItem,
} from "@/lib/types";

export const navigationItems: NavigationItem[] = [
  { label: "Home", href: "#", icon: "home" },
  { label: "Explore", href: "#", icon: "compass" },
  { label: "New Research", mobileLabel: "New Research", href: "#", icon: "plus" },
  { label: "My Research", href: "#", icon: "file" },
  { label: "Bookmarks", href: "#", icon: "bookmark" },
  { label: "Profile", href: "/profile", icon: "user" },
];

export const feedTabs = ["For You", "Following Hashtags", "Latest"] as const;

export const posts: ResearchPost[] = [
  {
    id: "remote-team-planning",
    initials: "LM",
    author: "Lena Morales",
    role: "UX Researcher",
    time: "18m",
    goal: "Collect Survey",
    goalStyle: "bg-sky-50 text-sky-700 ring-sky-100",
    avatarStyle: "bg-gradient-to-br from-orange-200 to-rose-300 text-rose-900",
    title: "How do remote teams actually prepare for Monday?",
    description: "I’m exploring the rituals people use to plan their week across time zones. This 4-minute survey will shape an async planning tool for distributed teams.",
    responseMethod: "external",
    externalLink: "https://example.com/research/remote-team-planning",
    hashtags: ["RemoteWork", "Productivity", "FutureOfWork"],
    estimatedTime: "4 min",
    targetAudience: ["Remote team members", "Team leads"],
    responseMode: "limited",
    responseTarget: 120,
    responseCount: 82,
    timeMode: "no_deadline",
    interestedCount: 34,
    participantCount: 18,
    commentCount: 12,
    shareCount: 6,
  },
  {
    id: "first-time-managers",
    initials: "NO",
    author: "Noah Okafor",
    role: "Founder at Sway",
    time: "1h",
    goal: "Find Interview Participants",
    goalStyle: "bg-violet-50 text-violet-700 ring-violet-100",
    avatarStyle: "bg-gradient-to-br from-teal-200 to-emerald-300 text-emerald-900",
    title: "Looking for first-time managers at growing startups",
    description: "Building a coaching product for new managers. I’d love to speak with 6 people who started managing a team within the last year. 30 minutes, remote, with a $25 thank-you.",
    responseMethod: "external",
    externalLink: "https://example.com/research/first-time-managers",
    hashtags: ["Leadership", "Startups", "UserResearch"],
    estimatedTime: "30 min",
    targetAudience: ["First-time managers", "Startup employees"],
    responseMode: "unlimited",
    responseCount: 3,
    timeMode: "no_deadline",
    interestedCount: 47,
    participantCount: 29,
    commentCount: 16,
    shareCount: 11,
  },
  {
    id: "pricing-prototype",
    initials: "AC",
    author: "Avery Chen",
    role: "Product Designer",
    time: "3h",
    goal: "Prototype Test",
    goalStyle: "bg-amber-50 text-amber-700 ring-amber-100",
    avatarStyle: "bg-gradient-to-br from-indigo-200 to-violet-300 text-indigo-900",
    title: "Can you find the right plan without second-guessing?",
    description: "We redesigned the pricing flow for a personal finance app. Try three quick tasks in our prototype and tell us where the options feel clear—or confusing.",
    responseMethod: "external",
    externalLink: "https://example.com/research/pricing-prototype",
    hashtags: ["Fintech", "UXTesting", "Prototype"],
    estimatedTime: "5 min",
    targetAudience: ["Finance app users", "Young professionals"],
    responseMode: "limited",
    responseTarget: 20,
    responseCount: 14,
    timeMode: "deadline",
    deadline: "2026-07-20",
    interestedCount: 26,
    participantCount: 41,
    commentCount: 9,
    shareCount: 4,
  },
  {
    id: "balcony-gardens",
    initials: "SK",
    author: "Samira Khan",
    role: "Climate Entrepreneur",
    time: "Yesterday",
    goal: "Validate Business Idea",
    goalStyle: "bg-emerald-50 text-emerald-700 ring-emerald-100",
    avatarStyle: "bg-gradient-to-br from-yellow-200 to-amber-300 text-amber-900",
    title: "Would renters pay for a shared balcony garden service?",
    description: "The idea: seasonal plants, monthly care, and shared harvests for apartment buildings. I’m testing willingness to pay before piloting in two neighborhoods.",
    responseMethod: "native",
    formQuestions: [
      { id: "garden-interest", type: "multiple_choice", label: "Would you use a shared balcony garden service?", required: true, options: ["Yes", "Maybe", "No"] },
      { id: "garden-priority", type: "checkbox", label: "What would matter most to you?", required: true, options: ["Monthly care", "Shared harvests", "Seasonal plants", "Low price"] },
      { id: "garden-notes", type: "paragraph", label: "What would make this service useful for your building?", required: false },
    ],
    hashtags: ["ClimateTech", "UrbanLiving", "BusinessValidation"],
    estimatedTime: "7 min",
    targetAudience: ["Apartment renters", "Urban gardeners"],
    responseMode: "unlimited",
    responseCount: 31,
    timeMode: "no_deadline",
    interestedCount: 63,
    participantCount: 52,
    commentCount: 24,
    shareCount: 15,
  },
  {
    id: "onboarding-dashboard-feedback",
    initials: "DT",
    author: "Diego Torres",
    role: "Product Lead at Northstar",
    time: "Yesterday",
    goal: "Design Feedback",
    goalStyle: "bg-rose-50 text-rose-700 ring-rose-100",
    avatarStyle: "bg-gradient-to-br from-sky-200 to-blue-300 text-blue-900",
    title: "Does this analytics dashboard make the next step obvious?",
    description: "We’re simplifying onboarding analytics for small product teams. I’m looking for quick feedback on hierarchy, labels, and whether the first recommended action feels clear.",
    responseMethod: "external",
    externalLink: "https://example.com/research/analytics-dashboard",
    hashtags: ["ProductDesign", "Analytics", "DesignFeedback"],
    estimatedTime: "6 min",
    targetAudience: ["Product Managers", "Startup Founders", "UX Designers"],
    responseMode: "limited",
    responseTarget: 30,
    responseCount: 11,
    timeMode: "deadline",
    deadline: "2026-07-24",
    interestedCount: 22,
    participantCount: 8,
    commentCount: 7,
    shareCount: 3,
  },
];

export const trendingResearch: TrendingResearchItem[] = [
  { title: "AI research tools", postCount: 128 },
  { title: "Sustainable products", postCount: 86 },
  { title: "Remote team culture", postCount: 64 },
];

export const popularHashtags = [
  "UserResearch",
  "BuildInPublic",
  "UXTesting",
  "Startups",
  "ProductDesign",
  "Survey",
];

export const quickStartItems: QuickStartItem[] = [
  { goal: "Design Feedback", dotClassName: "bg-rose-400" },
  { goal: "Prototype Test", dotClassName: "bg-amber-400" },
  { goal: "Validate Business Idea", dotClassName: "bg-blue-500" },
];
